### ISSUE TITLE
On form, ensure tab key doesn't move beyond the last item but cycles to first item again

### ISSUE THREAD

**Issue by dgarvin57** [dgarvin57/g3tools-dj-ui#10]
Currently, after reaching the last element (button), the next click of the tab key leaves the form and selects something in the browser outside the application.

**Comment by bmassey** [comment]
I've run into this before but haven't spent a lot of time to try and fix it.  I'm curious how best to handle this.

**Comment by dgarvin57** [comment]
I think it works when I route to the page with the form rather than
hide/unhide. I'm moving towards routing. I'll see if it's still a problem.

**Comment by dgarvin57** [comment]
Confirmed that using routing to display detail page solves this problem.

**Comment by dgarvin57** [comment]
Confirmed that using routing to display detail page solves this problem.
